### ISSUE TITLE
Image service via Open Source Service

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-naip#10]
http://wiki.openstreetmap.org/wiki/National_Agriculture_Imagery_Program gives an example of using WMS and TMS in openstreet maps.  Is TMS the most open format for imagery?  What are the requirements for this service?  What would we use for the server backend? Preprocessing? Can users use this service to get science ready imagery.  How does this compare to open http://wiki.openstreetmap.org/wiki/OpenAerialMap, and their reboot?  The Jan2015 discussion identifies a number of TMS server implementations we could look at.

**Comment by wildintellect** [comment]
TMS like tiles is the most common method of service (Often called XYZ layers, they are not 100% OSGeo TMS spec). Upside it's just tiles, nothing else. There are plenty of fast implementations.
Only requirement is that is responds to urls like tile.opencyclemap.org/cycle/{z}/{x}/{y}.png z = zoom, x and y being the tile row and column http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

You can't really trust either TMS or WMS for science ready data, that requires WCS. Most servers that do WMS also do WCS and WMTS(the actual replacement based on OSGeo TMS). Mapserver and Geoserver being the most common.

I'm happy to discuss more as I've been to most of the recent OpenAerialMap meetings.

**Comment by ghost** [comment]
@wildintellect @qjhart I would be very happy to discuss this with you, especially as I have prior Geoserver WMTS experience. When would you have time?

**Comment by ghost** [comment]
@qjhart The downside being that WMTS differs from imagery and is available at only specified zoom levels.

**Comment by qjhart** [comment]
@gwatprg regarding this notion of science ready, is that even an issue with NAIP? Is there a correspondance with the RGB or NRG images with specific radiances at all?

**Comment by ghost** [comment]
@qjhart I think these are two different issues, if I am understanding you correctly. We can talk more when you are in. 
Regarding science ready, it depends on how you want the service used. I am sure you already know this, but WMTS service provides prerendered images, essentially pictures, at specified zoom levels, which would be compatible for using as a baselayer. Setting up WCS service, provides the raster data and may allow filtering, selecting different bands, processing...hence more usable for scientific visualization and query (depending on how it is set up).
Regarding the 2005 RGB and NRG, I have also spoken with FSA. The NRG should really not be combined with RGB. It was acquired through a separate contract with the vendor. There are differences. I can follow up with the vendor some more.

**Comment by qjhart** [comment]
All that is understood.  My question is only about radiance.  Do we have radiometrically correct images that need to be modified to look good as images, or are the images already modified to look good, so we have no knowledge of the radiometric values.

**Comment by ghost** [comment]
@qjhart let me find out more about radiometric correction. After having no response to my first email, I called the vendor that supplied the 2005 data this morning to get more information about the cir vs natural color products and what processing was done on them. I have two new email contacts doug.cain@nwgeo.com and jodi.delorme@nwgeo.com. I was warned that Jodi is out for the week. Will see if I can get some more info on at least the 2005 data. I see what I can find about radiometric correction as well.

**Comment by ghost** [comment]
@qjhart I'm not sure if this is what you want. From what I have read, images are modified before being delivered to the NAIP program. For example, here are the specifications from 2007 http://www.fsa.usda.gov/Internet/FSA_File/naip_best_practice.pdf The image processing part starts on page 17. The specifications were revised again in 2012. The metadata that comes with the images gives limited information about the processing, i.e. for 2014 "SURDEX software was used to color correct and remove bidirectional reflectance, vignetting and other  illumination trends.  USDA APFO Image Metrics are measured and  images corrected to conform to the Image Metrics using SURDEX software…. SURDEX software was used to adjust for minor radiometric variation between adjacent images."

**Comment by qjhart** [comment]
That's all good information, from that I say we do not need to worry about using the original files for any radiometric regions.

**Comment by ghost** [comment]
@qjhart sounds good to me.
