### ISSUE TITLE
Service Review

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-naip#3]
We need to decide between ESRI servics and [OpenStreetMap](http://wiki.openstreetmap.org/wiki/National_Agriculture_Imagery_Program)

If we go that route, need to consider CIR as well.

**Comment by ghost** [comment]
@qjhart BTW if you go to https://github.com/ucd-cws/ca-naip/blob/master/public/CA_NAIP_2012.geojson  and zoom in, you can see githubs default behavior - it should bring up a popup. I am starting a customized Leaflet viewer with the geojson which won't be public for a while. I am still having trouble loading the external geojson file.

**Comment by qjhart** [comment]
Superceded with #8, #9 #10
