### ISSUE TITLE
Standardize Naming Conventions

### ISSUE THREAD

**Issue by ghost** [ucd-cws/ca-naip#4]
Define naming convention, original name versus USGS name versus state naming convention.

**Comment by qjhart** [comment]
@gwatprg currently we use the USGS naming scheme for holind our data, but use the other (old USGS?) naming scheme (the alpha-number) code for distribution.  I think we should continue with this setup, and maybe just publish a quick javascript example that goes from one to the other?

**Comment by ghost** [comment]
@qjhart Along with other naming differences, I was trying to write a script to check for missing files. I notice the filenames from the FSA quad indexes are different from the filenames that we have, i.e. n_3211403_se_11_1_20050626_20060127.tif (FSA quad index)  n_3211403_se_11_1_20050626.tif (our file). I'll have to look at doing this differently.

**Comment by ghost** [comment]
@qjhart I have a preliminary javascript file to convert from the one naming convention to the other, assuming one is passing in something like 32114a1 or 3211464. https://github.com/ucd-cws/ca-naip/blob/gh-pages/js/convertName.js Not sure if this is what you had in mind.

**Comment by qjhart** [comment]
This is fine as along as you can access it via the method used to create the symbolic links to our data, unless we are not going to have those links, and only make that connection via the index file?  Maybe that's not such a bad solution
