### ISSUE TITLE
Get 2014 NAIP imagery

### ISSUE THREAD

**Issue by ghost** [ucd-cws/ca-naip#5]
Acquire 2014 NAIP imagery from another source on campus or USGS

**Comment by qjhart** [comment]
http://liaisons.usgs.gov/geospatial/California/ shows Carol's contact information.

**Comment by ghost** [comment]
Picked up drives from Will Patterson and gave them to George yesterday.

**Comment by ghost** [comment]
@qjhart George finished copying the files over to temporary storage, and I returned the drives this afternoon.
